/**Constructor
 *  it is the special type of method which will gettinng executed
 *  at the time of object creation.
 * 
 * The constructor is used to initialize the object
 * 
 */

// class Demo{
//     Demo(){
//         System.out.println("constructor");
//     }
//     public static void main(String args[]){
//         Demo d = new Demo();
//     }
// }



/**Rules:-
 * 1- The constructor name and the class name must be same.
 * 2- The return type concept is not applicable for constructor ,
 *      if we are trying to provide return type then it will become a method.
 * 3- All the access modifier are applicable for constructor, but non-access modifiers are not allowed
 * 4- constructor cant be inherit.
 * 5- constructor cant be override
 */

/*  *Types of constructor*
 * 1- Parameterized constructor
 * 2- non-parameterized Constructor
 */

// class Demo{
//     Demo(int x){
//         System.out.println("constructor");
//     }
//     public static void main(String args[]){
//         // Demo d = new Demo();
//         Demo d2 = new Demo(10);
//         Demo d3 = new Demo('d');
//         Demo d4 = new Demo((int)2.3);

//     }
// }



/**Default Constructor*
 *-> it is the special type off constructor generated by compiler ,
 *  whenever there is no user defined constructor present inside our class.
 * -> The default constructor will always be of non-parameterized type.
 * -> There is only one statement inside default constructor that is called to super().
 * ->Every default constructor is a non-parameterized constructor but every 
 *      non-parameterized constructor is not default constructor.
 * ->The modifier which is applicable for class (only acess modifier ) is also 
 *      applicable for default constructor.
 */



// class Demo{
//     Demo(){
//         System.out.println("constructor");
//     }
//     public static void main(String args[]){
//         Demo d = new Demo();
//     }
// }


/**Constructor Overloading
 * Creating multiple constructor with same name but different kind of argument
 *  is the concept of constructor overloading.
 */

// class Demo{
//     Demo(){
//         System.out.println("constructor 1");
//     }
//     Demo(int x){
//         System.out.println("constructor 2");
//     }
//     Demo(String s){
//         System.out.println("constructor 3");
//     }
//     public static void main(String args[]){
//         Demo d = new Demo();
//         Demo d2 = new Demo(12);
//         Demo d3 = new Demo("hello");
//     }
// }


